#lang typed/racket

#|
    Knotty, a domain specific language for knitting patterns.
    Copyright (C) 2021-3 Tom Price

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
|#

(provide (all-defined-out))

(require racket/fixnum
         threading)
(require "global.rkt"
         "logger.rkt"
         "util.rkt")

(log-message knotty-logger 'info "start of colors.rkt" #f)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; 24 bit RGB number to name of approximate color
(: rgb->name : Nonnegative-Fixnum -> String)
(define (rgb->name rgb)
  (let* ([r : Byte (bitwise-and (fxrshift rgb 16) #xFF)]
         [g : Byte (bitwise-and (fxrshift rgb  8) #xFF)]
         [b : Byte (bitwise-and           rgb     #xFF)]
         [r~ (bitcrunch r)]
         [g~ (bitcrunch g)]
         [b~ (bitcrunch b)]
         [rgb~ (bitwise-ior
                (fxlshift r~ 8)
                (fxlshift g~ 4)
                b~)])
    (get-color rgb~)))

;; reduce color channel resolution from 8 to 4 bits
(: bitcrunch : Byte -> Byte)
(define (bitcrunch x)
  (let* ([hi-nibble : Byte (bitwise-and x #xF0)]
         [lo-nibble : Byte (bitwise-and
                            (fxrshift hi-nibble 4)
                            #x0F)]
         [x~ : Byte (bitwise-ior
                     hi-nibble
                     lo-nibble)]
         [d (- x x~)]
         [nearest
          (cond [(<= (abs d) 8) x~]
                [(positive? d)  (byte-sum #x11 x~)]
                [else           (byte-sum #xEF x~)])])
    (~> nearest
        (fxrshift 4)
        (bitwise-and #x0F))))

;; get color name from vector
(: get-color : Nonnegative-Fixnum -> String)
(define (get-color rgb)
  (if (> rgb #xFFFFFF)
      ""
      (let ([sym (vector-ref named-colors rgb)])
        (remove-hyphen sym))))


;; Some edits were necessary:
;; Screamin' Green -> Screaming
;; Robin's Egg Blue -> Robin
;; Davy's Grey -> Davys
;; Baker's Chocolate -> Bakers
;; Purple Mountain's Majesty -> Mountain
;; Jackson's Purple -> Jacksons
;; Mandy's Pink -> Mandys
;; Tony's Pink -> Tonys
;; Patten's Blue -> Pattens
;; Earl's Green -> Earls
;; Santa's Grey -> Santas
;; Horse's Neck -> Horses
;; Paris M -> Metro (apparent typo)
(define named-colors : (Immutable-Vectorof Symbol)
  (vector-immutable
    'Black
    'Black-Russian
    'Black-Russian
    'Midnight-Express
    'Midnight-Express
    'Navy
    'Navy
    'Navy
    'Dark-Blue
    'New-Midnight-Blue
    'New-Midnight-Blue
    'Medium-Blue
    'Medium-Blue
    'Medium-Blue
    'Blue
    'Blue
    'Black-Bean
    'Dark-Green
    'Black-Pearl
    'Midnight-Express
    'Midnight-Express
    'Sapphire
    'Sapphire
    'Navy
    'Dark-Blue
    'New-Midnight-Blue
    'New-Midnight-Blue
    'Medium-Blue
    'Medium-Blue
    'Medium-Blue
    'Blue
    'Blue
    'Myrtle
    'Dark-Green
    'Dark-Green
    'Black-Pearl
    'Tangaroa
    'Sapphire
    'Sapphire
    'Sapphire
    'Smalt
    'Smalt
    'International-Klein-Blue
    'International-Klein-Blue
    'Medium-Blue
    'Medium-Blue
    'Blue
    'Blue
    'Myrtle
    'Dark-Green
    'Dark-Green
    'Cyprus
    'Sherpa-Blue
    'Prussian-Blue
    'Prussian-Blue
    'Prussian-Blue
    'Smalt
    'Smalt
    'International-Klein-Blue
    'International-Klein-Blue
    'Persian-Blue
    'Persian-Blue
    'Blue
    'Blue
    'Myrtle
    'British-Racing-Green
    'British-Racing-Green
    'British-Racing-Green
    'Sherpa-Blue
    'Sherpa-Blue
    'Prussian-Blue
    'Dark-Cerulean
    'Dark-Cerulean
    'Cobalt
    'Cobalt
    'Cobalt
    'Cobalt
    'Navy-Blue
    'Navy-Blue
    'Navy-Blue
    'Green
    'British-Racing-Green
    'British-Racing-Green
    'British-Racing-Green
    'Cyprus
    'Mosque
    'Blue-Lagoon
    'Blue-Lagoon
    'Dark-Cerulean
    'Cobalt
    'Cobalt
    'Cobalt
    'Navy-Blue
    'Navy-Blue
    'Navy-Blue
    'Navy-Blue
    'Green
    'Green
    'Crusoe
    'Fun-Green
    'Watercourse
    'Mosque
    'Mosque
    'Blue-Lagoon
    'Blue-Lagoon
    'Cerulean
    'Cerulean
    'Navy-Blue
    'Navy-Blue
    'Navy-Blue
    'Navy-Blue
    'Navy-Blue
    'Green
    'Green
    'Crusoe
    'Dark-Spring-Green
    'Watercourse
    'Watercourse
    'Tropical-Rain-Forest
    'Surfie-Green
    'Teal
    'Cerulean
    'Cerulean
    'Cerulean
    'Navy-Blue
    'Navy-Blue
    'Navy-Blue
    'Dodger-Blue
    'Green
    'Green
    'Forest-Green
    'Dark-Spring-Green
    'Salem
    'Shamrock-Green
    'Observatory
    'Observatory
    'Dark-Cyan
    'Eastern-Blue
    'Eastern-Blue
    'Bondi-Blue
    'Pacific-Blue
    'Pacific-Blue
    'Dodger-Blue
    'Dodger-Blue
    'Islamic-Green
    'Islamic-Green
    'Islamic-Green
    'Pigment-Green
    'Pigment-Green
    'Shamrock-Green
    'Shamrock-Green
    'Free-Speech-Aquamarine
    'Persian-Green
    'Persian-Green
    'Bondi-Blue
    'Bondi-Blue
    'Pacific-Blue
    'Pacific-Blue
    'Dodger-Blue
    'Dodger-Blue
    'Islamic-Green
    'Islamic-Green
    'Dark-Pastel-Green
    'Dark-Pastel-Green
    'Pigment-Green
    'Pigment-Green
    'Jade
    'Jade
    'Persian-Green
    'Persian-Green
    'Persian-Green
    'Iris-Blue
    'Iris-Blue
    'Iris-Blue
    'Deep-Sky-Blue
    'Deep-Sky-Blue
    'Islamic-Green
    'Islamic-Green
    'Dark-Pastel-Green
    'Dark-Pastel-Green
    'Dark-Pastel-Green
    'Pigment-Green
    'Jade
    'Jade
    'Caribbean-Green
    'Caribbean-Green
    'Caribbean-Green
    'Iris-Blue
    'Iris-Blue
    'Iris-Blue
    'Deep-Sky-Blue
    'Deep-Sky-Blue
    'Free-Speech-Green
    'Free-Speech-Green
    'Dark-Pastel-Green
    'Dark-Pastel-Green
    'Dark-Pastel-Green
    'Malachite
    'Malachite
    'Caribbean-Green
    'Caribbean-Green
    'Caribbean-Green
    'Caribbean-Green
    'Robin-Egg-Blue
    'Robin-Egg-Blue
    'Dark-Turquoise
    'Deep-Sky-Blue
    'Deep-Sky-Blue
    'Lime
    'Free-Speech-Green
    'Free-Speech-Green
    'Dark-Pastel-Green
    'Malachite
    'Malachite
    'Malachite
    'Spring-Green
    'Caribbean-Green
    'Caribbean-Green
    'Caribbean-Green
    'Robin-Egg-Blue
    'Dark-Turquoise
    'Bright-Turquoise
    'Bright-Turquoise
    'Deep-Sky-Blue
    'Lime
    'Free-Speech-Green
    'Free-Speech-Green
    'Malachite
    'Malachite
    'Malachite
    'Spring-Green
    'Spring-Green
    'Spring-Green
    'Medium-Spring-Green
    'Medium-Spring-Green
    'Medium-Spring-Green
    'Bright-Turquoise
    'Bright-Turquoise
    'Bright-Turquoise
    'Aqua
    'Lime
    'Free-Speech-Green
    'Free-Speech-Green
    'Free-Speech-Green
    'Malachite
    'Malachite
    'Spring-Green
    'Spring-Green
    'Spring-Green
    'Medium-Spring-Green
    'Medium-Spring-Green
    'Medium-Spring-Green
    'Bright-Turquoise
    'Bright-Turquoise
    'Aqua
    'Aqua
    'Black
    'Mardi-Gras
    'Blackcurrant
    'Blackcurrant
    'Violent-Violet
    'Midnight-Blue
    'Midnight-Blue
    'Navy
    'Ultramarine
    'Ultramarine
    'New-Midnight-Blue
    'Medium-Blue
    'Medium-Blue
    'Medium-Blue
    'Blue
    'Blue
    'Maire
    'Black
    'Black-Russian
    'Black-Russian
    'Midnight-Express
    'Midnight-Blue
    'Midnight-Blue
    'Midnight-Blue
    'Ultramarine
    'Ultramarine
    'New-Midnight-Blue
    'Medium-Blue
    'Medium-Blue
    'Medium-Blue
    'Blue
    'Blue
    'Pine-Tree
    'Black-Bean
    'Swamp
    'Black-Pearl
    'Midnight-Express
    'Sapphire
    'Sapphire
    'Midnight-Blue
    'Midnight-Blue
    'Egyptian-Blue
    'Egyptian-Blue
    'Persian-Blue
    'Persian-Blue
    'Medium-Blue
    'Blue
    'Blue
    'Myrtle
    'Myrtle
    'Cardin-Green
    'Nordic
    'Blue-Whale
    'Regal-Blue
    'Sapphire
    'Sapphire
    'Smalt
    'Egyptian-Blue
    'Egyptian-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Blue
    'Myrtle
    'Myrtle
    'Deep-Fir
    'Sherwood-Green
    'Cyprus
    'Astronaut-Blue
    'Astronaut-Blue
    'Dark-Cerulean
    'Dark-Cerulean
    'Egyptian-Blue
    'Egyptian-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Neon-Blue
    'Myrtle
    'Myrtle
    'Crusoe
    'Crusoe
    'Deep-Teal
    'Blue-Stone
    'Blue-Lagoon
    'Orient
    'Dark-Cerulean
    'Endeavour
    'Cobalt
    'Denim
    'Denim
    'Navy-Blue
    'Navy-Blue
    'Navy-Blue
    'Green
    'Green
    'Crusoe
    'Crusoe
    'Jewel
    'Blue-Stone
    'Blue-Stone
    'Allports
    'Allports
    'Cerulean
    'Denim
    'Denim
    'Denim
    'Navy-Blue
    'Navy-Blue
    'Dodger-Blue
    'Green
    'Green
    'Forest-Green
    'Camarone
    'Dark-Spring-Green
    'Salem
    'Deep-Sea
    'Surfie-Green
    'Allports
    'Cerulean
    'Cerulean
    'Denim
    'Navy-Blue
    'Navy-Blue
    'Dodger-Blue
    'Dodger-Blue
    'Green
    'Forest-Green
    'Forest-Green
    'Forest-Green
    'Salem
    'Salem
    'Elf-Green
    'Elf-Green
    'Dark-Cyan
    'Eastern-Blue
    'Eastern-Blue
    'Bondi-Blue
    'Pacific-Blue
    'Dodger-Blue
    'Dodger-Blue
    'Dodger-Blue
    'Islamic-Green
    'Islamic-Green
    'Forest-Green
    'Forest-Green
    'Pigment-Green
    'Pigment-Green
    'Shamrock-Green
    'Free-Speech-Aquamarine
    'Persian-Green
    'Java
    'Bondi-Blue
    'Bondi-Blue
    'Pacific-Blue
    'Pacific-Blue
    'Dodger-Blue
    'Dodger-Blue
    'Islamic-Green
    'Islamic-Green
    'Forest-Green
    'Dark-Pastel-Green
    'Pigment-Green
    'Pigment-Green
    'Jade
    'Mountain-Meadow
    'Mountain-Meadow
    'Persian-Green
    'Light-Sea-Green
    'Iris-Blue
    'Iris-Blue
    'Iris-Blue
    'Deep-Sky-Blue
    'Deep-Sky-Blue
    'Islamic-Green
    'Islamic-Green
    'Dark-Pastel-Green
    'Dark-Pastel-Green
    'Dark-Pastel-Green
    'Pigment-Green
    'Jade
    'Mountain-Meadow
    'Mountain-Meadow
    'Caribbean-Green
    'Light-Sea-Green
    'Iris-Blue
    'Iris-Blue
    'Iris-Blue
    'Deep-Sky-Blue
    'Deep-Sky-Blue
    'Free-Speech-Green
    'Free-Speech-Green
    'Dark-Pastel-Green
    'Dark-Pastel-Green
    'Dark-Pastel-Green
    'Malachite
    'Malachite
    'Mountain-Meadow
    'Caribbean-Green
    'Caribbean-Green
    'Caribbean-Green
    'Robin-Egg-Blue
    'Robin-Egg-Blue
    'Dark-Turquoise
    'Deep-Sky-Blue
    'Deep-Sky-Blue
    'Free-Speech-Green
    'Free-Speech-Green
    'Free-Speech-Green
    'Malachite
    'Malachite
    'Malachite
    'Malachite
    'Spring-Green
    'Caribbean-Green
    'Caribbean-Green
    'Caribbean-Green
    'Robin-Egg-Blue
    'Bright-Turquoise
    'Bright-Turquoise
    'Bright-Turquoise
    'Deep-Sky-Blue
    'Free-Speech-Green
    'Free-Speech-Green
    'Free-Speech-Green
    'Free-Speech-Green
    'Malachite
    'Malachite
    'Malachite
    'Spring-Green
    'Spring-Green
    'Medium-Spring-Green
    'Medium-Spring-Green
    'Bright-Turquoise
    'Bright-Turquoise
    'Bright-Turquoise
    'Bright-Turquoise
    'Aqua
    'Lime
    'Free-Speech-Green
    'Free-Speech-Green
    'Free-Speech-Green
    'Malachite
    'Malachite
    'Spring-Green
    'Spring-Green
    'Spring-Green
    'Medium-Spring-Green
    'Medium-Spring-Green
    'Medium-Spring-Green
    'Bright-Turquoise
    'Bright-Turquoise
    'Aqua
    'Aqua
    'Seal-Brown
    'Blackberry
    'Mardi-Gras
    'Blackcurrant
    'Blackcurrant
    'Violent-Violet
    'Persian-Indigo
    'Persian-Indigo
    'Ultramarine
    'Ultramarine
    'Ultramarine
    'Medium-Blue
    'Medium-Blue
    'Medium-Blue
    'Blue
    'Blue
    'Cocoa-Brown
    'Seal-Brown
    'Mardi-Gras
    'Blackcurrant
    'Violent-Violet
    'Violent-Violet
    'Midnight-Blue
    'Midnight-Blue
    'Ultramarine
    'Ultramarine
    'Ultramarine
    'Medium-Blue
    'Medium-Blue
    'Medium-Blue
    'Blue
    'Blue
    'Maire
    'Maire
    'Nero
    'Jaguar
    'Valhalla
    'Paua
    'Midnight-Blue
    'Midnight-Blue
    'Midnight-Blue
    'Ultramarine
    'Egyptian-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Blue
    'Blue
    'Pine-Tree
    'Pine-Tree
    'Myrtle
    'Swamp
    'Midnight
    'Catalina-Blue
    'Catalina-Blue
    'Resolution-Blue
    'Resolution-Blue
    'Egyptian-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Neon-Blue
    'Turtle-Green
    'Myrtle
    'Myrtle
    'Everglade
    'Tiber
    'Astronaut-Blue
    'Regal-Blue
    'Fun-Blue
    'Fun-Blue
    'Egyptian-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Cerulean-Blue
    'Neon-Blue
    'Neon-Blue
    'Myrtle
    'Myrtle
    'Myrtle
    'Kaitoke-Green
    'Te-Papa-Green
    'Dark-Slate-Grey
    'Arapawa
    'Orient
    'Endeavour
    'Endeavour
    'Cerulean-Blue
    'Cerulean-Blue
    'Cerulean-Blue
    'Cerulean-Blue
    'Royal-Blue
    'Royal-Blue
    'Green
    'Myrtle
    'San-Felix
    'Camarone
    'Green-Pea
    'Eden
    'Blue-Stone
    'Allports
    'Allports
    'Lochmara
    'Lochmara
    'Denim
    'Denim
    'Royal-Blue
    'Royal-Blue
    'Royal-Blue
    'Green
    'Forest-Green
    'Forest-Green
    'San-Felix
    'Dark-Spring-Green
    'Salem
    'Deep-Sea
    'Elm
    'Allports
    'Lochmara
    'Lochmara
    'Denim
    'Denim
    'Royal-Blue
    'Dodger-Blue
    'Dodger-Blue
    'Forest-Green
    'Forest-Green
    'Forest-Green
    'Forest-Green
    'Sea-Green
    'Sea-Green
    'Elf-Green
    'Elf-Green
    'Java
    'Scooter
    'Scooter
    'Pelorous
    'Curious-Blue
    'Dodger-Blue
    'Dodger-Blue
    'Dodger-Blue
    'Islamic-Green
    'Forest-Green
    'Forest-Green
    'Forest-Green
    'Sea-Green
    'Sea-Green
    'Eucalyptus
    'Elf-Green
    'Niagara
    'Java
    'Pelorous
    'Pelorous
    'Pelorous
    'Summer-Sky
    'Dodger-Blue
    'Dodger-Blue
    'Islamic-Green
    'Forest-Green
    'Forest-Green
    'Forest-Green
    'Chateau-Green
    'Eucalyptus
    'Eucalyptus
    'Jungle-Green
    'Jungle-Green
    'Niagara
    'Light-Sea-Green
    'Pelorous
    'Summer-Sky
    'Summer-Sky
    'Summer-Sky
    'Dodger-Blue
    'Kelly-Green
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Dark-Pastel-Green
    'Malachite
    'Medium-Sea-Green
    'Mountain-Meadow
    'Mountain-Meadow
    'Niagara
    'Light-Sea-Green
    'Light-Sea-Green
    'Iris-Blue
    'Summer-Sky
    'Summer-Sky
    'Deep-Sky-Blue
    'Kelly-Green
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Malachite
    'Malachite
    'Mountain-Meadow
    'Shamrock
    'Shamrock
    'Shamrock
    'Light-Sea-Green
    'Robin-Egg-Blue
    'Dark-Turquoise
    'Summer-Sky
    'Deep-Sky-Blue
    'Free-Speech-Green
    'Free-Speech-Green
    'Lime-Green
    'Lime-Green
    'Malachite
    'Malachite
    'Malachite
    'Shamrock
    'Shamrock
    'Shamrock
    'Shamrock
    'Turquoise
    'Turquoise
    'Bright-Turquoise
    'Bright-Turquoise
    'Deep-Sky-Blue
    'Harlequin
    'Free-Speech-Green
    'Free-Speech-Green
    'Lime-Green
    'Malachite
    'Malachite
    'Malachite
    'Spring-Green
    'Spring-Green
    'Medium-Spring-Green
    'Medium-Spring-Green
    'Turquoise
    'Bright-Turquoise
    'Bright-Turquoise
    'Bright-Turquoise
    'Aqua
    'Harlequin
    'Free-Speech-Green
    'Free-Speech-Green
    'Free-Speech-Green
    'Malachite
    'Malachite
    'Spring-Green
    'Spring-Green
    'Spring-Green
    'Medium-Spring-Green
    'Medium-Spring-Green
    'Medium-Spring-Green
    'Bright-Turquoise
    'Bright-Turquoise
    'Bright-Turquoise
    'Aqua
    'Seal-Brown
    'Rustic-Red
    'Blackberry
    'Mardi-Gras
    'Blackcurrant
    'Blackcurrant
    'Persian-Indigo
    'Persian-Indigo
    'Persian-Indigo
    'Persian-Indigo
    'Ultramarine
    'Ultramarine
    'Medium-Blue
    'Han-Purple
    'Han-Purple
    'Han-Purple
    'Brown-Pod
    'Seal-Brown
    'Blackberry
    'Mardi-Gras
    'Blackcurrant
    'Christalle
    'Christalle
    'Persian-Indigo
    'Persian-Indigo
    'Persian-Indigo
    'Ultramarine
    'Persian-Blue
    'Medium-Blue
    'Han-Purple
    'Han-Purple
    'Han-Purple
    'Black-Magic
    'Cocoa-Brown
    'Nero
    'Mardi-Gras
    'Violent-Violet
    'Violent-Violet
    'Paris-Metro
    'Persian-Indigo
    'Persian-Indigo
    'Dark-Slate-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Han-Purple
    'Han-Purple
    'Han-Purple
    'Karaka
    'Karaka
    'Karaka
    'Night-Rider
    'Revolver
    'Lucky-Point
    'Deep-Koamaru
    'Torea-Bay
    'Jacksons-Purple
    'Dark-Slate-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Persian-Blue
    'Neon-Blue
    'Neon-Blue
    'Turtle-Green
    'Turtle-Green
    'Seaweed
    'Timber-Green
    'Firefly
    'Rhino
    'Gulf-Blue
    'Resolution-Blue
    'Tory-Blue
    'Tory-Blue
    'Cerulean-Blue
    'Cerulean-Blue
    'Free-Speech-Blue
    'Free-Speech-Blue
    'Neon-Blue
    'Neon-Blue
    'Verdun-Green
    'Seaweed
    'Palm-Leaf
    'Parsley
    'Plantation
    'Oracle
    'Blumine
    'Venice-Blue
    'St-Tropaz
    'Tory-Blue
    'Cerulean-Blue
    'Cerulean-Blue
    'Free-Speech-Blue
    'Royal-Blue
    'Royal-Blue
    'Neon-Blue
    'Verdun-Green
    'Bilbao
    'Green-House
    'San-Felix
    'Green-Pea
    'Spectra
    'Tax-Break
    'Blumine
    'Astral
    'Lochmara
    'Lochmara
    'Cerulean-Blue
    'Royal-Blue
    'Royal-Blue
    'Royal-Blue
    'Royal-Blue
    'Bilbao
    'Bilbao
    'Bilbao
    'Japanese-Laurel
    'Amazon
    'Amazon
    'Genoa
    'Atoll
    'Astral
    'Lochmara
    'Lochmara
    'Curious-Blue
    'Curious-Blue
    'Royal-Blue
    'Royal-Blue
    'Dodger-Blue
    'Bilbao
    'Bilbao
    'Bilbao
    'Japanese-Laurel
    'Amazon
    'Sea-Green
    'Viridian
    'Genoa
    'Blue-Chill
    'Scooter
    'Scooter
    'Curious-Blue
    'Curious-Blue
    'Curious-Blue
    'Dodger-Blue
    'Dodger-Blue
    'La-Palma
    'La-Palma
    'La-Palma
    'Forest-Green
    'Chateau-Green
    'Eucalyptus
    'Eucalyptus
    'Gossamer
    'Gossamer
    'Java
    'Scooter
    'Pelorous
    'Summer-Sky
    'Summer-Sky
    'Dodger-Blue
    'Dodger-Blue
    'Kelly-Green
    'Kelly-Green
    'Kelly-Green
    'Lime-Green
    'Fruit-Salad
    'Chateau-Green
    'Medium-Sea-Green
    'Medium-Sea-Green
    'Jungle-Green
    'Niagara
    'Light-Sea-Green
    'Pelorous
    'Summer-Sky
    'Summer-Sky
    'Summer-Sky
    'Dodger-Blue
    'Kelly-Green
    'Kelly-Green
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Chateau-Green
    'Medium-Sea-Green
    'Medium-Sea-Green
    'Jungle-Green
    'Shamrock
    'Light-Sea-Green
    'Light-Sea-Green
    'Summer-Sky
    'Summer-Sky
    'Summer-Sky
    'Summer-Sky
    'Kelly-Green
    'Kelly-Green
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Medium-Sea-Green
    'Medium-Sea-Green
    'Shamrock
    'Shamrock
    'Shamrock
    'Medium-Turquoise
    'Medium-Turquoise
    'Medium-Turquoise
    'Summer-Sky
    'Summer-Sky
    'Harlequin
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Malachite
    'Emerald
    'Emerald
    'Shamrock
    'Shamrock
    'Shamrock
    'Turquoise
    'Turquoise
    'Turquoise
    'Turquoise
    'Turquoise
    'Harlequin
    'Harlequin
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Malachite
    'Malachite
    'Emerald
    'Shamrock
    'Shamrock
    'Shamrock
    'Turquoise
    'Turquoise
    'Turquoise
    'Turquoise
    'Turquoise
    'Harlequin
    'Harlequin
    'Harlequin
    'Lime-Green
    'Lime-Green
    'Screaming-Green
    'Screaming-Green
    'Spring-Green
    'Spring-Green
    'Medium-Spring-Green
    'Medium-Spring-Green
    'Turquoise
    'Turquoise
    'Turquoise
    'Turquoise
    'Aqua
    'Seal-Brown
    'Rustic-Red
    'Blackberry
    'Blackberry
    'Mardi-Gras
    'Blackcurrant
    'Indigo
    'Indigo
    'Indigo
    'Indigo
    'Indigo
    'Purple-Heart
    'Han-Purple
    'Han-Purple
    'Han-Purple
    'Han-Purple
    'Brown-Pod
    'Seal-Brown
    'Bordeaux
    'Blackberry
    'Mardi-Gras
    'Scarlet-Gum
    'Christalle
    'Indigo
    'Indigo
    'Indigo
    'Indigo
    'Purple-Heart
    'Purple-Heart
    'Han-Purple
    'Han-Purple
    'Han-Purple
    'Bistre
    'Brown-Pod
    'Espresso
    'Toledo
    'Valentino
    'Scarlet-Gum
    'Christalle
    'Windsor
    'Windsor
    'Blue-Gem
    'Blue-Gem
    'Purple-Heart
    'Purple-Heart
    'Han-Purple
    'Han-Purple
    'Han-Purple
    'Mikado
    'Mikado
    'Clinker
    'Cowboy
    'Fuscous-Grey
    'Jagger
    'Meteorite
    'Windsor
    'Dark-Slate-Blue
    'Blue-Gem
    'Blue-Gem
    'Purple-Heart
    'Purple-Heart
    'Han-Purple
    'Neon-Blue
    'Neon-Blue
    'Verdun-Green
    'Verdun-Green
    'El-Paso
    'Waiouru
    'Charcoal
    'Gun-Powder
    'Corn-Flower-Blue
    'Corn-Flower-Blue
    'Jacksons-Purple
    'Dark-Slate-Blue
    'Governor-Bay
    'Free-Speech-Blue
    'Free-Speech-Blue
    'Free-Speech-Blue
    'Neon-Blue
    'Neon-Blue
    'Verdun-Green
    'Verdun-Green
    'Bronzetone
    'Clover
    'Grey-Asparagus
    'Dark-Slate
    'San-Juan
    'Chambray
    'Tory-Blue
    'Governor-Bay
    'Governor-Bay
    'Free-Speech-Blue
    'Free-Speech-Blue
    'Royal-Blue
    'Neon-Blue
    'Neon-Blue
    'Verdun-Green
    'Verdun-Green
    'Dell
    'Dell
    'Grey-Asparagus
    'Viridian-Green
    'Tax-Break
    'Bismark
    'Wedgewood
    'Mariner
    'Mariner
    'Free-Speech-Blue
    'Free-Speech-Blue
    'Royal-Blue
    'Royal-Blue
    'Neon-Blue
    'Bilbao
    'Bilbao
    'Bilbao
    'Bilbao
    'Killarney
    'Como
    'Viridian
    'Ming
    'Jelly-Bean
    'Jelly-Bean
    'Steel-Blue
    'Steel-Blue
    'Havelock-Blue
    'Royal-Blue
    'Royal-Blue
    'Royal-Blue
    'Bilbao
    'La-Palma
    'La-Palma
    'La-Palma
    'Killarney
    'Como
    'Viridian
    'Viridian
    'Paradiso
    'Hippie-Blue
    'Boston-Blue
    'Curious-Blue
    'Curious-Blue
    'Havelock-Blue
    'Cornflower-Blue
    'Cornflower-Blue
    'Kelly-Green
    'La-Palma
    'La-Palma
    'La-Palma
    'Fruit-Salad
    'Chateau-Green
    'Chateau-Green
    'Gossamer
    'Lochinvar
    'Blue-Chill
    'Boston-Blue
    'Boston-Blue
    'Picton-Blue
    'Picton-Blue
    'Cornflower-Blue
    'Cornflower-Blue
    'Kelly-Green
    'Kelly-Green
    'Kelly-Green
    'La-Palma
    'Fruit-Salad
    'Fruit-Salad
    'Ocean-Green
    'Ocean-Green
    'Gossamer
    'Gossamer
    'Cadet-Blue
    'Viking
    'Viking
    'Summer-Sky
    'Summer-Sky
    'Summer-Sky
    'Kelly-Green
    'Kelly-Green
    'Kelly-Green
    'Lime-Green
    'Fruit-Salad
    'Fruit-Salad
    'Medium-Sea-Green
    'Medium-Sea-Green
    'Medium-Sea-Green
    'Puerto-Rico
    'Puerto-Rico
    'Viking
    'Viking
    'Summer-Sky
    'Summer-Sky
    'Summer-Sky
    'Kelly-Green
    'Kelly-Green
    'Kelly-Green
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Emerald
    'Emerald
    'Emerald
    'Shamrock
    'Shamrock
    'Medium-Turquoise
    'Medium-Turquoise
    'Medium-Turquoise
    'Summer-Sky
    'Summer-Sky
    'Harlequin
    'Kelly-Green
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Lime-Green
    'Emerald
    'Emerald
    'Emerald
    'Shamrock
    'Shamrock
    'Turquoise
    'Turquoise
    'Turquoise
    'Turquoise
    'Turquoise-Blue
    'Harlequin
    'Harlequin
    'Harlequin
    'Lime-Green
    'Lime-Green
    'Screaming-Green
    'Screaming-Green
    'Emerald
    'Emerald
    'Shamrock
    'Shamrock
    'Turquoise
    'Turquoise
    'Turquoise
    'Turquoise
    'Baby-Blue
    'Harlequin
    'Harlequin
    'Harlequin
    'Harlequin
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Shamrock
    'Shamrock
    'Turquoise
    'Turquoise
    'Turquoise
    'Turquoise
    'Baby-Blue
    'Maroon
    'Bordeaux
    'Blackberry
    'Tyrian-Purple
    'Tyrian-Purple
    'Tyrian-Purple
    'Indigo
    'Indigo
    'Indigo
    'Indigo
    'Indigo
    'Purple-Heart
    'Purple-Heart
    'Electric-Indigo
    'Electric-Indigo
    'Electric-Indigo
    'Red-Oxide
    'Red-Oxide
    'Bordeaux
    'Blackberry
    'Tyrian-Purple
    'Hot-Purple
    'Scarlet-Gum
    'Indigo
    'Indigo
    'Indigo
    'Purple-Heart
    'Purple-Heart
    'Purple-Heart
    'Han-Purple
    'Han-Purple
    'Han-Purple
    'Bakers-Chocolate
    'Caput-Mortuum
    'Red-Oxide
    'Black-Rose
    'Loulou
    'Hot-Purple
    'Scarlet-Gum
    'Blue-Diamond
    'Kingfisher-Daisy
    'Daisy-Bush
    'Purple-Heart
    'Purple-Heart
    'Purple-Heart
    'Han-Purple
    'Han-Purple
    'Han-Purple
    'Bakers-Chocolate
    'Bakers-Chocolate
    'Brown-Bramble
    'Van-Cleef
    'Barossa
    'Hot-Purple
    'Honey-Flower
    'Kingfisher-Daisy
    'Kingfisher-Daisy
    'Daisy-Bush
    'Daisy-Bush
    'Purple-Heart
    'Purple-Heart
    'Purple-Heart
    'Han-Purple
    'Han-Purple
    'Bronze-Olive
    'Bronze-Olive
    'Bronze-Olive
    'Deep-Bronze
    'Woody-Brown
    'Bossanova
    'Honey-Flower
    'Gigas
    'Gigas
    'Blue-Gem
    'Rich-Blue
    'Rich-Blue
    'Slate-Blue
    'Slate-Blue
    'Neon-Blue
    'Neon-Blue
    'Verdun-Green
    'Army-Green
    'Saratoga
    'Camouflage
    'Ship-Grey
    'Matterhorn
    'Smoky
    'Comet
    'Governor-Bay
    'Governor-Bay
    'Rich-Blue
    'Rich-Blue
    'Slate-Blue
    'Slate-Blue
    'Neon-Blue
    'Neon-Blue
    'Verdun-Green
    'Fiji-Green
    'Dark-Olive-Green
    'Dark-Olive-Green
    'Chalet-Green
    'Nandor
    'River-Bed
    'Shuttle-Grey
    'Kashmir-Blue
    'San-Marino
    'Rich-Blue
    'Chetwode-Blue
    'Free-Speech-Blue
    'Royal-Blue
    'Royal-Blue
    'Neon-Blue
    'Fiji-Green
    'Fiji-Green
    'Green-Leaf
    'Green-Leaf
    'Fern-Green
    'Killarney
    'Como
    'Breaker-Bay
    'Hoki
    'San-Marino
    'San-Marino
    'Havelock-Blue
    'Havelock-Blue
    'Royal-Blue
    'Royal-Blue
    'Royal-Blue
    'Olive-Drab
    'Vida-Loca
    'Vida-Loca
    'Vida-Loca
    'Fern-Green
    'Hippie-Green
    'Como
    'Cutty-Sark
    'Half-Baked
    'Hippie-Blue
    'Air-Force-Blue
    'Danube
    'Havelock-Blue
    'Cornflower-Blue
    'Cornflower-Blue
    'Cornflower-Blue
    'Limeade
    'Limeade
    'Limeade
    'Limeade
    'Hippie-Green
    'Fruit-Salad
    'Chateau-Green
    'Ocean-Green
    'Patina
    'Half-Baked
    'Cadet-Blue
    'Shakespeare
    'Picton-Blue
    'Picton-Blue
    'Cornflower-Blue
    'Cornflower-Blue
    'Kelly-Green
    'Kelly-Green
    'Kelly-Green
    'Apple
    'Apple
    'Fruit-Salad
    'Fern
    'Ocean-Green
    'Keppel
    'Keppel
    'Cadet-Blue
    'Viking
    'Viking
    'Picton-Blue
    'Malibu
    'Cornflower-Blue
    'Kelly-Green
    'Kelly-Green
    'Kelly-Green
    'Apple
    'Apple
    'Fruit-Salad
    'Fern
    'Emerald
    'Silver-Tree
    'Keppel
    'Puerto-Rico
    'Fountain-Blue
    'Viking
    'Malibu
    'Malibu
    'Maya-Blue
    'Kelly-Green
    'Kelly-Green
    'Kelly-Green
    'Kelly-Green
    'Apple
    'Fern
    'Emerald
    'Emerald
    'Emerald
    'Medium-Aquamarine
    'Medium-Aquamarine
    'Medium-Turquoise
    'Medium-Turquoise
    'Medium-Turquoise
    'Turquoise-Blue
    'Maya-Blue
    'Bright-Green
    'Kelly-Green
    'Kelly-Green
    'Lime-Green
    'Lime-Green
    'Screaming-Green
    'Emerald
    'Emerald
    'Emerald
    'Medium-Aquamarine
    'Medium-Aquamarine
    'Downy
    'Medium-Turquoise
    'Medium-Turquoise
    'Turquoise-Blue
    'Turquoise-Blue
    'Bright-Green
    'Bright-Green
    'Bright-Green
    'Lime-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Emerald
    'Medium-Aquamarine
    'Medium-Aquamarine
    'Turquoise
    'Turquoise
    'Turquoise
    'Turquoise-Blue
    'Baby-Blue
    'Bright-Green
    'Bright-Green
    'Harlequin
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Medium-Aquamarine
    'Medium-Aquamarine
    'Aquamarine
    'Turquoise
    'Turquoise
    'Baby-Blue
    'Baby-Blue
    'Maroon
    'Burgundy
    'Burgundy
    'Tyrian-Purple
    'Tyrian-Purple
    'Tyrian-Purple
    'Purple
    'Purple
    'Indigo
    'Indigo
    'Indigo
    'Purple-Heart
    'Purple-Heart
    'Electric-Indigo
    'Electric-Indigo
    'Electric-Indigo
    'Maroon
    'Red-Oxide
    'Pohutukawa
    'Tyrian-Purple
    'Tyrian-Purple
    'Palatinate-Purple
    'Palatinate-Purple
    'Seance
    'Indigo
    'Indigo
    'Purple-Heart
    'Purple-Heart
    'Purple-Heart
    'Electric-Indigo
    'Electric-Indigo
    'Electric-Indigo
    'Bakers-Chocolate
    'Caput-Mortuum
    'Red-Oxide
    'Claret
    'Pompadour
    'Palatinate-Purple
    'Palatinate-Purple
    'Seance
    'Kingfisher-Daisy
    'Royal-Purple
    'Purple-Heart
    'Purple-Heart
    'Purple-Heart
    'Purple-Heart
    'Han-Purple
    'Han-Purple
    'Bakers-Chocolate
    'Bakers-Chocolate
    'Hairy-Heath
    'Persian-Plum
    'Tawny-Port
    'Palatinate-Purple
    'Seance
    'Eminence
    'Kingfisher-Daisy
    'Royal-Purple
    'Royal-Purple
    'Purple-Heart
    'Purple-Heart
    'Purple-Heart
    'Han-Purple
    'Han-Purple
    'Raw-Umber
    'Raw-Umber
    'Dark-Brown
    'Jambalaya
    'Congo-Brown
    'Finn
    'Seance
    'Honey-Flower
    'Daisy-Bush
    'Royal-Purple
    'Royal-Purple
    'Purple-Heart
    'Slate-Blue
    'Slate-Blue
    'Neon-Blue
    'Neon-Blue
    'Raw-Umber
    'Raw-Umber
    'Horses-Neck
    'Horses-Neck
    'Tobacco-Brown
    'Zambezi
    'Fedora
    'Mobster
    'Butterfly-Bush
    'Butterfly-Bush
    'Blue-Marguerite
    'Blue-Marguerite
    'Slate-Blue
    'Slate-Blue
    'Medium-Slate-Blue
    'Neon-Blue
    'Olive
    'Fiji-Green
    'Costa-Del-Sol
    'Verdigris
    'Hemlock
    'Hemlock
    'Dim-Gray
    'Comet
    'Comet
    'Scampi
    'Chetwode-Blue
    'Chetwode-Blue
    'Slate-Blue
    'Slate-Blue
    'Medium-Slate-Blue
    'Medium-Slate-Blue
    'Olive
    'Fiji-Green
    'Fiji-Green
    'Rain-Forest
    'Chalet-Green
    'Willow-Grove
    'Finlandia
    'Nevada
    'Lynch
    'Waikawa-Grey
    'Chetwode-Blue
    'Chetwode-Blue
    'Chetwode-Blue
    'Cornflower-Blue
    'Medium-Slate-Blue
    'Light-Slate-Blue
    'Olive
    'Olive-Drab
    'Olive-Drab
    'Vida-Loca
    'Dingley
    'Glade-Green
    'Laurel
    'Cutty-Sark
    'Gumbo
    'Horizon
    'Air-Force-Blue
    'Danube
    'Danube
    'Cornflower-Blue
    'Cornflower-Blue
    'Cornflower-Blue
    'Christi
    'Olive-Drab
    'Limeade
    'Limeade
    'Apple
    'Hippie-Green
    'Laurel
    'Oxley
    'Patina
    'Cadet-Blue
    'Shakespeare
    'Shakespeare
    'Picton-Blue
    'Cornflower-Blue
    'Cornflower-Blue
    'Cornflower-Blue
    'Christi
    'Christi
    'Christi
    'Limeade
    'Apple
    'Apple
    'Fern
    'Oxley
    'Acapulco
    'Keppel
    'Fountain-Blue
    'Fountain-Blue
    'Picton-Blue
    'Malibu
    'Malibu
    'Cornflower-Blue
    'Christi
    'Christi
    'Christi
    'Apple
    'Apple
    'Apple
    'Fern
    'Fern
    'Silver-Tree
    'Keppel
    'Puerto-Rico
    'Fountain-Blue
    'Seagull
    'Malibu
    'Malibu
    'Maya-Blue
    'Kelly-Green
    'Kelly-Green
    'Kelly-Green
    'Apple
    'Apple
    'Apple
    'Fern
    'Fern
    'Silver-Tree
    'Silver-Tree
    'Medium-Aquamarine
    'Downy
    'Downy
    'Turquoise-Blue
    'Turquoise-Blue
    'Maya-Blue
    'Bright-Green
    'Bright-Green
    'Kelly-Green
    'Apple
    'Apple
    'Screaming-Green
    'Pastel-Green
    'Pastel-Green
    'Pastel-Green
    'Medium-Aquamarine
    'Medium-Aquamarine
    'Downy
    'Downy
    'Turquoise-Blue
    'Turquoise-Blue
    'Turquoise-Blue
    'Bright-Green
    'Bright-Green
    'Bright-Green
    'Bright-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Pastel-Green
    'Medium-Aquamarine
    'Medium-Aquamarine
    'Downy
    'Aquamarine
    'Turquoise-Blue
    'Turquoise-Blue
    'Baby-Blue
    'Bright-Green
    'Bright-Green
    'Bright-Green
    'Bright-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Light-Green
    'Aquamarine
    'Aquamarine
    'Aquamarine
    'Aquamarine
    'Baby-Blue
    'Baby-Blue
    'Maroon
    'Burgundy
    'Burgundy
    'Tyrian-Purple
    'Tyrian-Purple
    'Tyrian-Purple
    'Purple
    'Purple
    'Purple
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Violet
    'Dark-Violet
    'Dark-Violet
    'Electric-Indigo
    'Electric-Indigo
    'Maroon
    'Falu-Red
    'Red-Berry
    'Claret
    'Pompadour
    'Pompadour
    'Dark-Purple
    'Purple
    'Purple
    'Dark-Magenta
    'Purple-Heart
    'Purple-Heart
    'Dark-Violet
    'Blue-Violet
    'Electric-Indigo
    'Electric-Indigo
    'Falu-Red
    'Falu-Red
    'Lusty
    'Claret
    'Flirt
    'Flirt
    'Palatinate-Purple
    'Dark-Purple
    'Vivid-Violet
    'Vivid-Violet
    'Royal-Purple
    'Purple-Heart
    'Purple-Heart
    'Blue-Violet
    'Blue-Violet
    'Blue-Violet
    'Raw-Umber
    'Peru-Tan
    'Pueblo
    'Lusty
    'Camelot
    'Flirt
    'Palatinate-Purple
    'Eminence
    'Vivid-Violet
    'Vivid-Violet
    'Royal-Purple
    'Purple-Heart
    'Purple-Heart
    'Blue-Violet
    'Blue-Violet
    'Blue-Violet
    'Raw-Umber
    'Raw-Umber
    'Peru-Tan
    'Peanut
    'Bole
    'Finn
    'Cosmic
    'Eminence
    'Affair
    'Studio
    'Studio
    'Studio
    'Purple-Heart
    'Slate-Blue
    'Blue-Violet
    'Medium-Slate-Blue
    'Raw-Umber
    'Raw-Umber
    'Hot-Curry
    'Shingle-Fawn
    'Old-Copper
    'Buccaneer
    'Cosmic
    'Trendy-Pink
    'Affair
    'Studio
    'Studio
    'Blue-Marguerite
    'Slate-Blue
    'Slate-Blue
    'Medium-Slate-Blue
    'Medium-Slate-Blue
    'Olive
    'Yukon-Gold
    'Yukon-Gold
    'Himalaya
    'Yellow-Metal
    'Pine-Cone
    'Pharlap
    'Old-Lavender
    'Mamba
    'Scampi
    'Scampi
    'Blue-Marguerite
    'Slate-Blue
    'Medium-Slate-Blue
    'Medium-Slate-Blue
    'Light-Slate-Blue
    'Olive
    'Olive
    'Olivetone
    'Crete
    'Hemlock
    'Kokoda
    'Tapa
    'Grey
    'Storm-Grey
    'Scampi
    'Chetwode-Blue
    'Moody-Blue
    'Moody-Blue
    'Medium-Slate-Blue
    'Medium-Slate-Blue
    'Light-Slate-Blue
    'Olive
    'Trendy-Green
    'Trendy-Green
    'Wasabi
    'Wasabi
    'Highland
    'Camouflage-Green
    'Davys-Grey
    'Juniper
    'Light-Slate-Grey
    'Ship-Cove
    'Wild-Blue-Yonder
    'Wild-Blue-Yonder
    'Portage
    'Cornflower-Blue
    'Cornflower-Blue
    'Olive
    'Christi
    'Sushi
    'Sushi
    'Sushi
    'Asparagus
    'Highland
    'Davys-Grey
    'Granny-Smith
    'Juniper
    'Bali-Hai
    'Bali-Hai
    'Polo-Blue
    'Jordy-Blue
    'Cornflower-Blue
    'Cornflower-Blue
    'Christi
    'Christi
    'Lima
    'Sushi
    'Asparagus
    'Asparagus
    'Amulet
    'Amulet
    'Bay-Leaf
    'Acapulco
    'Neptune
    'Glacier
    'Seagull
    'Jordy-Blue
    'Jordy-Blue
    'Maya-Blue
    'Christi
    'Lima
    'Lima
    'Lima
    'Apple
    'Mantis
    'Mantis
    'Fern
    'Bay-Leaf
    'Padua
    'Gulf-Stream
    'Glacier
    'Seagull
    'Seagull
    'Maya-Blue
    'Maya-Blue
    'Christi
    'Lima
    'Lima
    'Apple
    'Mantis
    'Mantis
    'Mantis
    'Pastel-Green
    'De-York
    'Silver-Tree
    'Medium-Aquamarine
    'Downy
    'Spray
    'Spray
    'Sky-Blue
    'Maya-Blue
    'Lawn-Green
    'Lawn-Green
    'Yellow-Green
    'Yellow-Green
    'Mantis
    'Mantis
    'Pastel-Green
    'Pastel-Green
    'Pastel-Green
    'Silver-Tree
    'Medium-Aquamarine
    'Downy
    'Riptide
    'Turquoise-Blue
    'Turquoise-Blue
    'Light-Sky-Blue
    'Lawn-Green
    'Lawn-Green
    'Lawn-Green
    'Atlantis
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Pastel-Green
    'Pastel-Green
    'Light-Green
    'Vista-Blue
    'Aquamarine
    'Aquamarine
    'Aquamarine
    'Electric-Blue
    'Electric-Blue
    'Lawn-Green
    'Lawn-Green
    'Lawn-Green
    'Lawn-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Screaming-Green
    'Light-Green
    'Light-Green
    'Mint-Green
    'Aquamarine
    'Aquamarine
    'Aquamarine
    'Baby-Blue
    'Baby-Blue
    'Dark-Red
    'Sangria
    'Burgundy
    'Burgundy
    'Tyrian-Purple
    'Eggplant
    'Eggplant
    'Purple
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Violet
    'Dark-Violet
    'Dark-Violet
    'Dark-Violet
    'Electric-Indigo
    'Dark-Red
    'Falu-Red
    'Burgundy
    'Scarlett
    'Disco
    'Eggplant
    'Eggplant
    'Dark-Purple
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Violet
    'Dark-Violet
    'Dark-Violet
    'Blue-Violet
    'Electric-Indigo
    'Falu-Red
    'Falu-Red
    'Mandarian-Orange
    'Shiraz
    'Disco
    'Rose-Bud-Cherry
    'Dark-Purple
    'Dark-Purple
    'Dark-Purple
    'Vivid-Violet
    'Vivid-Violet
    'Dark-Orchid
    'Dark-Orchid
    'Blue-Violet
    'Blue-Violet
    'Blue-Violet
    'Saddle-Brown
    'Saddle-Brown
    'Burnt-Umber
    'Tall-Poppy
    'Camelot
    'Rose-Bud-Cherry
    'Rose-Bud-Cherry
    'Dark-Purple
    'Vivid-Violet
    'Vivid-Violet
    'Vivid-Violet
    'Dark-Orchid
    'Dark-Orchid
    'Blue-Violet
    'Blue-Violet
    'Blue-Violet
    'Saddle-Brown
    'Saddle-Brown
    'Russet
    'Paarl
    'Matrix
    'Camelot
    'Cosmic
    'Trendy-Pink
    'Vivid-Violet
    'Vivid-Violet
    'Deep-Lilac
    'Deep-Lilac
    'Dark-Orchid
    'Blue-Violet
    'Blue-Violet
    'Blue-Violet
    'Raw-Umber
    'Saddle-Brown
    'Hot-Curry
    'Rope
    'Ironstone
    'Lotus
    'Cannon-Pink
    'Strikemaster
    'Trendy-Pink
    'Affair
    'Deep-Lilac
    'Deep-Lilac
    'Amethyst
    'Medium-Purple
    'Medium-Slate-Blue
    'Light-Slate-Blue
    'Golden-Brown
    'Yukon-Gold
    'Yukon-Gold
    'McKenzie
    'Dark-Wood
    'Leather
    'Light-Wood
    'Strikemaster
    'Trendy-Pink
    'Ce-Soir
    'Ce-Soir
    'Lilac-Bush
    'True-V
    'Medium-Purple
    'Medium-Slate-Blue
    'Light-Slate-Blue
    'Olive
    'Yukon-Gold
    'Corn-Harvest
    'Corn-Harvest
    'Shadow
    'Shadow
    'Sand-Dune
    'Bazaar
    'Old-Lavender
    'Topaz
    'Deluge
    'True-V
    'Moody-Blue
    'Medium-Purple
    'Light-Slate-Blue
    'Light-Slate-Blue
    'Olive
    'Olive
    'Trendy-Green
    'Highball
    'Highball
    'Bandicoot
    'Bitter
    'Schist
    'Grey
    'Manatee
    'Manatee
    'Moody-Blue
    'Moody-Blue
    'Portage
    'Portage
    'Light-Slate-Blue
    'Olive
    'Citron
    'Citron
    'Wasabi
    'Wasabi
    'Chelsea-Cucumber
    'Chelsea-Cucumber
    'Amulet
    'Pewter
    'Submarine
    'Bali-Hai
    'Rock-Blue
    'Portage
    'Portage
    'Portage
    'Portage
    'Citrus
    'Limerick
    'Limerick
    'Limerick
    'Chelsea-Cucumber
    'Chelsea-Cucumber
    'Chelsea-Cucumber
    'Amulet
    'Envy
    'Padua
    'Ziggurat
    'Nepal
    'Polo-Blue
    'Jordy-Blue
    'Jordy-Blue
    'Jordy-Blue
    'Citrus
    'Lima
    'Limerick
    'Limerick
    'Chelsea-Cucumber
    'Mantis
    'Mantis
    'Mantis
    'Dark-Sea-Green
    'Summer-Green
    'Sea-Nymph
    'Glacier
    'Seagull
    'Seagull
    'Cornflower
    'Light-Sky-Blue
    'Citrus
    'Citrus
    'Yellow-Green
    'Yellow-Green
    'Atlantis
    'Mantis
    'Mantis
    'De-York
    'De-York
    'Summer-Green
    'Vista-Blue
    'Bermuda
    'Riptide
    'Spray
    'Sky-Blue
    'Light-Sky-Blue
    'Lawn-Green
    'Lawn-Green
    'Yellow-Green
    'Yellow-Green
    'Atlantis
    'Mantis
    'Mantis
    'Pastel-Green
    'De-York
    'Light-Green
    'Vista-Blue
    'Bermuda
    'Riptide
    'Spray
    'Sky-Blue
    'Light-Sky-Blue
    'Lawn-Green
    'Lawn-Green
    'Lawn-Green
    'Atlantis
    'Atlantis
    'Mantis
    'Pastel-Green
    'Pastel-Green
    'Light-Green
    'Light-Green
    'Vista-Blue
    'Vista-Blue
    'Aquamarine
    'Aquamarine
    'Electric-Blue
    'Electric-Blue
    'Chartreuse
    'Chartreuse
    'Chartreuse
    'Green-Yellow
    'Green-Yellow
    'Screaming-Green
    'Screaming-Green
    'Light-Green
    'Light-Green
    'Mint-Green
    'Mint-Green
    'Aquamarine
    'Aquamarine
    'Aquamarine
    'Electric-Blue
    'Electric-Blue
    'Dark-Red
    'Carmine
    'Carmine
    'Carmine
    'Jazzberry-Jam
    'Jazzberry-Jam
    'Eggplant
    'Eggplant
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Violet
    'Dark-Violet
    'Dark-Violet
    'Dark-Violet
    'Electric-Purple
    'Dark-Red
    'Falu-Red
    'Carmine
    'Bright-Red
    'Lipstick
    'Jazzberry-Jam
    'Jazzberry-Jam
    'Dark-Purple
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Violet
    'Dark-Violet
    'Dark-Violet
    'Dark-Violet
    'Blue-Violet
    'Falu-Red
    'Mandarian-Orange
    'Mandarian-Orange
    'Bright-Red
    'Lipstick
    'Lipstick
    'Lipstick
    'Dark-Purple
    'Dark-Purple
    'Vivid-Violet
    'Dark-Orchid
    'Dark-Orchid
    'Dark-Orchid
    'Blue-Violet
    'Blue-Violet
    'Blue-Violet
    'Saddle-Brown
    'Burnt-Umber
    'Burnt-Umber
    'Milano-Red
    'Well-Read
    'Lipstick
    'Lipstick
    'Dark-Purple
    'Dark-Purple
    'Vivid-Violet
    'Vivid-Violet
    'Dark-Orchid
    'Dark-Orchid
    'Dark-Orchid
    'Blue-Violet
    'Blue-Violet
    'Saddle-Brown
    'Saddle-Brown
    'Rock-Spray
    'Tia-Maria
    'Roof-Terracotta
    'Night-Shadz
    'Cadillac
    'Rouge
    'Violet-Blue
    'Violet-Blue
    'Deep-Lilac
    'Deep-Lilac
    'Dark-Orchid
    'Dark-Orchid
    'Blue-Violet
    'Blue-Violet
    'Golden-Brown
    'Golden-Brown
    'Rich-Gold
    'Piper
    'Sepia
    'Copper-Rust
    'Vin-Rouge
    'Strikemaster
    'Strikemaster
    'Violet-Blue
    'Deep-Lilac
    'Deep-Lilac
    'Amethyst
    'Amethyst
    'Medium-Purple
    'Light-Slate-Blue
    'Golden-Brown
    'Golden-Brown
    'Afghan-Tan
    'Mai-Tai
    'Dark-Tan
    'Au-Chico
    'Copper-Rose
    'Mauve-Taupe
    'Strikemaster
    'Violet-Blue
    'Ce-Soir
    'Deep-Lilac
    'Amethyst
    'Medium-Purple
    'Medium-Purple
    'Light-Slate-Blue
    'Golden-Brown
    'Hacienda
    'Hacienda
    'Buttered-Rum
    'Muesli
    'Pale-Brown
    'Toast
    'Opium
    'Mountbatten-Pink
    'Violet-Blue
    'Ce-Soir
    'Purple-Mountain-Majesty
    'Lilac-Bush
    'Medium-Purple
    'Medium-Purple
    'Light-Slate-Blue
    'Olive
    'Hacienda
    'Lemon-Ginger
    'Lemon-Ginger
    'Highball
    'Muesli
    'Pale-Oyster
    'Almond-Frost
    'Opium
    'Amethyst-Smoke
    'Purple-Mountain-Majesty
    'Cold-Purple
    'Cold-Purple
    'Medium-Purple
    'Medium-Purple
    'Light-Slate-Blue
    'Citrus
    'Citron
    'Citron
    'Highball
    'Highball
    'Avocado
    'Avocado
    'Malachite-Green
    'Lemon-Grass
    'Nobel
    'Santas-Grey
    'Logan
    'Blue-Bell
    'Blue-Bell
    'Portage
    'Portage
    'Citrus
    'Citrus
    'Citron
    'Limerick
    'Green-Smoke
    'Green-Smoke
    'Green-Smoke
    'Sage
    'Norway
    'Mantle
    'Hit-Grey
    'Nepal
    'Echo-Blue
    'Echo-Blue
    'Perano
    'Perano
    'Citrus
    'Citrus
    'Bahia
    'Yellow-Green
    'Atlantis
    'Chelsea-Cucumber
    'Olivine
    'Olivine
    'Norway
    'Dark-Sea-Green
    'Skeptic
    'Conch
    'Heather
    'Light-Steel-Blue
    'Perano
    'Perano
    'Citrus
    'Bahia
    'Yellow-Green
    'Yellow-Green
    'Atlantis
    'Atlantis
    'Olivine
    'Gossip
    'Gossip
    'Dark-Sea-Green
    'Chinook
    'Shadow-Green
    'Morning-Glory
    'Regent-St-Blue
    'Cornflower
    'Light-Sky-Blue
    'Inch-Worm
    'Inch-Worm
    'Yellow-Green
    'Atlantis
    'Atlantis
    'Conifer
    'Feijoa
    'Gossip
    'Granny-Smith-Apple
    'Granny-Smith-Apple
    'Chinook
    'Vista-Blue
    'Riptide
    'Morning-Glory
    'Blizzard-Blue
    'Columbia-Blue
    'Spring-Bud
    'Spring-Bud
    'Green-Yellow
    'Green-Yellow
    'Atlantis
    'Conifer
    'Feijoa
    'Feijoa
    'Granny-Smith-Apple
    'Light-Green
    'Celadon
    'Vista-Blue
    'Magic-Mint
    'Ice-Cold
    'Blizzard-Blue
    'Columbia-Blue
    'Spring-Bud
    'Spring-Bud
    'Green-Yellow
    'Green-Yellow
    'Green-Yellow
    'Green-Yellow
    'Feijoa
    'Light-Green
    'Mint-Green
    'Mint-Green
    'Mint-Green
    'Magic-Mint
    'Magic-Mint
    'Magic-Mint
    'Pale-Turquoise
    'Electric-Blue
    'Free-Speech-Red
    'Carmine
    'Carmine
    'Carmine
    'Jazzberry-Jam
    'Jazzberry-Jam
    'Jazzberry-Jam
    'Eggplant
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Violet
    'Dark-Violet
    'Dark-Violet
    'Electric-Purple
    'Electric-Purple
    'Free-Speech-Red
    'Fire-Brick
    'Carmine
    'Cardinal
    'Jazzberry-Jam
    'Jazzberry-Jam
    'Jazzberry-Jam
    'Jazzberry-Jam
    'Medium-Violet-Red
    'Dark-Magenta
    'Dark-Magenta
    'Dark-Violet
    'Dark-Violet
    'Dark-Violet
    'Electric-Purple
    'Electric-Purple
    'Rust
    'Fire-Brick
    'Fire-Brick
    'Guardsman-Red
    'Old-Rose
    'Lipstick
    'Jazzberry-Jam
    'Medium-Red-Violet
    'Medium-Red-Violet
    'Medium-Red-Violet
    'Dark-Orchid
    'Dark-Orchid
    'Dark-Orchid
    'Dark-Orchid
    'Blue-Violet
    'Electric-Purple
    'Rust
    'Rust
    'Brown
    'Milano-Red
    'Night-Shadz
    'Night-Shadz
    'Rouge
    'Medium-Red-Violet
    'Medium-Red-Violet
    'Medium-Red-Violet
    'Fuchsia
    'Dark-Orchid
    'Dark-Orchid
    'Dark-Orchid
    'Blue-Violet
    'Blue-Violet
    'Rust
    'Rust
    'Rose-Of-Sharon
    'Medium-Carmine
    'Roof-Terracotta
    'Hippie-Pink
    'Rouge
    'Royal-Heath
    'Medium-Red-Violet
    'Violet-Blue
    'Violet-Blue
    'Deep-Lilac
    'Medium-Orchid
    'Medium-Orchid
    'Medium-Orchid
    'Blue-Violet
    'Rust
    'Rich-Gold
    'Rich-Gold
    'Vesuvius
    'Crail
    'Apple-Blossom
    'Blush
    'Royal-Heath
    'Mulberry
    'Violet-Blue
    'Violet-Blue
    'Deep-Lilac
    'Medium-Orchid
    'Medium-Orchid
    'Medium-Orchid
    'Medium-Purple
    'Golden-Brown
    'Golden-Brown
    'Mai-Tai
    'Mai-Tai
    'Tuscany
    'Sante-Fe
    'Coral-Tree
    'Turkish-Rose
    'Tapestry
    'Violet-Blue
    'Violet-Blue
    'Deep-Lilac
    'Amethyst
    'Amethyst
    'Medium-Purple
    'Medium-Purple
    'Dark-Goldenrod
    'Dark-Goldenrod
    'Hot-Toddy
    'Hot-Toddy
    'Bourbon
    'Sante-Fe
    'Toast
    'Coral-Tree
    'Tapestry
    'Bouquet
    'Violet-Blue
    'East-Side
    'Amethyst
    'Medium-Purple
    'Medium-Purple
    'Medium-Purple
    'Dark-Goldenrod
    'Dark-Goldenrod
    'Hacienda
    'Reef-Gold
    'Luxor-Gold
    'Teak
    'Sandal
    'Sandrift
    'Thatch
    'Bouquet
    'London-Hue
    'East-Side
    'East-Side
    'Biloba-Flower
    'Biloba-Flower
    'Light-Slate-Blue
    'Lucky
    'Lucky
    'Lucky
    'Reef-Gold
    'Husk
    'Husk
    'Tallow
    'Tallow
    'Zorba
    'Dusty-Grey
    'London-Hue
    'East-Side
    'Biloba-Flower
    'Biloba-Flower
    'Biloba-Flower
    'Biloba-Flower
    'Citrus
    'Citrus
    'Earls-Green
    'Brass
    'Brass
    'Olive-Green
    'Olive-Green
    'Locust
    'Neutral-Green
    'Foggy-Grey
    'Dark-Gray
    'Logan
    'Wistful
    'Wistful
    'Perano
    'Perano
    'Citrus
    'Bahia
    'Bahia
    'Bahia
    'Celery
    'Celery
    'Olive-Green
    'Caper
    'Caper
    'Norway
    'Zanah
    'Jungle-Mist
    'Spindle
    'Light-Steel-Blue
    'Perano
    'Perano
    'Citrus
    'Bahia
    'Bahia
    'Yellow-Green
    'Atlantis
    'Conifer
    'Conifer
    'Caper
    'Feijoa
    'Spring-Rain
    'Zanah
    'Nebula
    'Jungle-Mist
    'French-Pass
    'Pale-Cornflower-Blue
    'Pale-Cornflower-Blue
    'Inch-Worm
    'Inch-Worm
    'Inch-Worm
    'Atlantis
    'Conifer
    'Conifer
    'Conifer
    'Feijoa
    'Feijoa
    'Granny-Smith-Apple
    'Moss-Green
    'Fringy-Flower
    'Ice-Cold
    'Powder-Blue
    'Light-Blue
    'Columbia-Blue
    'Spring-Bud
    'Inch-Worm
    'Inch-Worm
    'Green-Yellow
    'Conifer
    'Conifer
    'Conifer
    'Feijoa
    'Feijoa
    'Granny-Smith-Apple
    'Celadon
    'Fringy-Flower
    'Magic-Mint
    'Water-Leaf
    'Pale-Turquoise
    'Blizzard-Blue
    'Spring-Bud
    'Spring-Bud
    'Green-Yellow
    'Green-Yellow
    'Green-Yellow
    'Conifer
    'Conifer
    'Feijoa
    'Mint-Green
    'Mint-Green
    'Mint-Green
    'Fringy-Flower
    'Magic-Mint
    'Magic-Mint
    'Pale-Turquoise
    'Pale-Turquoise
    'Free-Speech-Red
    'Venetian-Red
    'Venetian-Red
    'Cardinal
    'Cardinal
    'Jazzberry-Jam
    'Jazzberry-Jam
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Deep-Magenta
    'Deep-Magenta
    'Deep-Magenta
    'Deep-Magenta
    'Electric-Purple
    'Electric-Purple
    'Free-Speech-Red
    'Free-Speech-Red
    'Fire-Engine-Red
    'Cardinal
    'Cardinal
    'Jazzberry-Jam
    'Jazzberry-Jam
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Deep-Magenta
    'Deep-Magenta
    'Deep-Magenta
    'Deep-Magenta
    'Electric-Purple
    'Electric-Purple
    'Harley-Davidson-Orange
    'Fire-Brick
    'Fire-Brick
    'Cardinal
    'Cardinal
    'Old-Rose
    'Jazzberry-Jam
    'Medium-Red-Violet
    'Medium-Red-Violet
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Deep-Magenta
    'Deep-Magenta
    'Dark-Orchid
    'Electric-Purple
    'Electric-Purple
    'Rust
    'Harley-Davidson-Orange
    'Harley-Davidson-Orange
    'Persian-Red
    'Old-Rose
    'Old-Rose
    'Rouge
    'Medium-Red-Violet
    'Medium-Red-Violet
    'Medium-Red-Violet
    'Fuchsia
    'Fuchsia
    'Medium-Orchid
    'Medium-Orchid
    'Medium-Orchid
    'Electric-Purple
    'Rust
    'Rust
    'Rust
    'Grenadier
    'Chestnut
    'Hippie-Pink
    'Blush
    'Royal-Heath
    'Mulberry
    'Mulberry
    'Fuchsia
    'Fuchsia
    'Medium-Orchid
    'Medium-Orchid
    'Medium-Orchid
    'Medium-Orchid
    'Tawny
    'Rust
    'Fiery-Orange
    'Smoke-Tree
    'Flame-Pea
    'Fuzzy-Wuzzy-Brown
    'Blush
    'Royal-Heath
    'Mulberry
    'Mulberry
    'Fuchsia
    'Fuchsia
    'Medium-Orchid
    'Medium-Orchid
    'Medium-Orchid
    'Medium-Orchid
    'Tawny
    'Chocolate
    'Christine
    'Christine
    'Tuscany
    'Sunglo
    'Contessa
    'Tapestry
    'Tapestry
    'Hopbush
    'Fuchsia
    'Fuchsia
    'Medium-Orchid
    'Medium-Orchid
    'Medium-Orchid
    'Heliotrope
    'Dark-Goldenrod
    'Dark-Goldenrod
    'Pirate-Gold
    'Meteor
    'Brandy-Punch
    'Red-Damask
    'Contessa
    'Contessa
    'Tapestry
    'Hopbush
    'Bouquet
    'Fuchsia
    'Medium-Orchid
    'Medium-Orchid
    'Heliotrope
    'Heliotrope
    'Dark-Goldenrod
    'Dark-Goldenrod
    'Nugget
    'Hokey-Pokey
    'Marigold
    'Twine
    'Medium-Wood
    'Brandy-Rose
    'Rosy-Brown
    'Viola
    'London-Hue
    'London-Hue
    'East-Side
    'Wisteria
    'Wisteria
    'Wisteria
    'Dark-Goldenrod
    'Buddha-Gold
    'Sahara
    'Nugget
    'Roti
    'Barley-Corn
    'Fallow
    'Pale-Taupe
    'Del-Rio
    'Rosy-Brown
    'Lily
    'Lilac
    'Wisteria
    'Perfume
    'Perfume
    'Perfume
    'La-Rioja
    'Earls-Green
    'Earls-Green
    'Brass
    'Brass
    'Gimblet
    'Gimblet
    'Ecru
    'Pavlova
    'Silk
    'Pink-Swan
    'Lola
    'Perfume
    'Moon-Raker
    'Melrose
    'Melrose
    'La-Rioja
    'La-Rioja
    'Rio-Grande
    'Old-Gold
    'Celery
    'Olive-Green
    'Dark-Khaki
    'Pine-Glade
    'Pine-Glade
    'Green-Mist
    'Mist-Grey
    'Silver
    'Lavender-Grey
    'Lavender-Grey
    'Lavender-Grey
    'Lavender-Blue
    'La-Rioja
    'Rio-Grande
    'Rio-Grande
    'Fuego
    'Celery
    'Wild-Willow
    'Wild-Willow
    'Pine-Glade
    'Caper
    'Sprout
    'Pixie-Green
    'Paris-White
    'Jungle-Mist
    'Spindle
    'Periwinkle
    'Periwinkle
    'Inch-Worm
    'Inch-Worm
    'Fuego
    'Fuego
    'Conifer
    'Conifer
    'Conifer
    'Sulu
    'Sulu
    'Pixie-Green
    'Madang
    'Surf
    'Aero-Blue
    'Powder-Blue
    'Light-Blue
    'Pale-Cornflower-Blue
    'Electric-Lime
    'Inch-Worm
    'Inch-Worm
    'Green-Yellow
    'Conifer
    'Conifer
    'Conifer
    'Sulu
    'Sulu
    'Madang
    'Madang
    'Fringy-Flower
    'Granny-Apple
    'Water-Leaf
    'Pale-Turquoise
    'Onahau
    'Electric-Lime
    'Electric-Lime
    'Green-Yellow
    'Green-Yellow
    'Green-Yellow
    'Conifer
    'Sulu
    'Sulu
    'Sulu
    'Madang
    'Madang
    'Fringy-Flower
    'Granny-Apple
    'Aero-Blue
    'Water-Leaf
    'Pale-Turquoise
    'Free-Speech-Red
    'Venetian-Red
    'Venetian-Red
    'Crimson
    'Crimson
    'Razzmatazz
    'Ruby
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Deep-Magenta
    'Deep-Magenta
    'Deep-Magenta
    'Deep-Magenta
    'Electric-Purple
    'Electric-Purple
    'Free-Speech-Red
    'Free-Speech-Red
    'Fire-Engine-Red
    'Cardinal
    'Crimson
    'Ruby
    'Ruby
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Deep-Magenta
    'Deep-Magenta
    'Deep-Magenta
    'Electric-Purple
    'Electric-Purple
    'Harley-Davidson-Orange
    'Harley-Davidson-Orange
    'Persian-Red
    'Cardinal
    'Cardinal
    'Old-Rose
    'Cerise
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Medium-Violet-Red
    'Deep-Magenta
    'Deep-Magenta
    'Deep-Magenta
    'Electric-Purple
    'Electric-Purple
    'Harley-Davidson-Orange
    'Harley-Davidson-Orange
    'Harley-Davidson-Orange
    'Persian-Red
    'Brick-Red
    'Old-Rose
    'Cerise
    'Deep-Cerise
    'Deep-Cerise
    'Deep-Cerise
    'Medium-Red-Violet
    'Fuchsia
    'Fuchsia
    'Medium-Orchid
    'Medium-Orchid
    'Electric-Purple
    'Tawny
    'Harley-Davidson-Orange
    'Trinidad
    'Trinidad
    'Sunset
    'Mandy
    'Cabaret
    'Cranberry
    'Mulberry
    'Mulberry
    'Mulberry
    'Fuchsia
    'Fuchsia
    'Medium-Orchid
    'Medium-Orchid
    'Heliotrope
    'Tawny
    'Tawny
    'Chilean-Fire
    'Trinidad
    'Dark-Coral
    'Fuzzy-Wuzzy-Brown
    'Cabaret
    'Cabaret
    'Mulberry
    'Mulberry
    'Fuchsia
    'Fuchsia
    'Fuchsia
    'Medium-Orchid
    'Medium-Orchid
    'Heliotrope
    'Tawny
    'Chocolate
    'Chocolate
    'Ecstasy
    'Red-Damask
    'Sunglo
    'Indian-Red
    'Cabaret
    'Hopbush
    'Hopbush
    'Hopbush
    'Fuchsia
    'Orchid
    'Orchid
    'Heliotrope
    'Heliotrope
    'Mango-Tango
    'Ochre
    'Ochre
    'Bronze
    'Raw-Sienna
    'Japonica
    'Japonica
    'Sea-Pink
    'Charm
    'Hopbush
    'Hopbush
    'Orchid
    'Orchid
    'Orchid
    'Heliotrope
    'Heliotrope
    'Dark-Goldenrod
    'Dark-Goldenrod
    'Geebung
    'Dixie
    'Peru
    'Whiskey-Sour
    'Burning-Sand
    'Feldspar
    'Oriental-Pink
    'Puce
    'Viola
    'Lily
    'Lilac
    'Wisteria
    'Wisteria
    'Heliotrope
    'Gamboge
    'Buddha-Gold
    'Buttercup
    'Fuel-Yellow
    'Anzac
    'Twine
    'Fallow
    'Feldspar
    'Quicksand
    'Petite-Orchid
    'Viola
    'Lily
    'Lilac
    'Wisteria
    'Wisteria
    'Mauve
    'Bird-Flower
    'Galliano
    'Galliano
    'Metallic-Gold
    'Sundance
    'Laser
    'Putty
    'Putty
    'Cameo
    'Eunry
    'Cold-Turkey
    'Maverick
    'Lilac
    'Wisteria
    'Perfume
    'Mauve
    'Bird-Flower
    'Bird-Flower
    'Barberry
    'Old-Gold
    'Old-Gold
    'Tacha
    'Tacha
    'Yuma
    'Yuma
    'Sour-Dough
    'Grain-Brown
    'Silver
    'Thistle
    'Moon-Raker
    'Fog
    'Lavender-Blue
    'La-Rioja
    'Bird-Flower
    'Barberry
    'Wattle
    'Wattle
    'Wild-Willow
    'Wild-Willow
    'Deco
    'Deco
    'Green-Mist
    'Orinoco
    'Moon-Mist
    'Very-Light-Grey
    'Lavender-Grey
    'Lavender-Blue
    'Lavender-Blue
    'Electric-Lime
    'Barberry
    'Pear
    'Pear
    'Las-Palmas
    'Wild-Willow
    'Mindaro
    'Deco
    'Sulu
    'Reef
    'Reef
    'Ottoman
    'Sea-Mist
    'Zumthor
    'Pattens-Blue
    'Hawkes-Blue
    'Electric-Lime
    'Electric-Lime
    'Pear
    'Pear
    'Pear
    'Mindaro
    'Mindaro
    'Sulu
    'Sulu
    'Reef
    'Reef
    'Tea-Green
    'Blue-Romance
    'Mint-Tulip
    'Oyster-Bay
    'Pattens-Blue
    'Electric-Lime
    'Electric-Lime
    'Electric-Lime
    'Pear
    'Pear
    'Mindaro
    'Mindaro
    'Sulu
    'Sulu
    'Reef
    'Tea-Green
    'Tea-Green
    'Blue-Romance
    'Cosmic-Latte
    'Humming-Bird
    'Light-Cyan
    'Free-Speech-Red
    'Venetian-Red
    'Venetian-Red
    'Crimson
    'Crimson
    'Razzmatazz
    'Razzmatazz
    'Ruby
    'Medium-Violet-Red
    'Hollywood-Cerise
    'Hollywood-Cerise
    'Deep-Magenta
    'Deep-Magenta
    'Deep-Magenta
    'Psychedelic-Purple
    'Psychedelic-Purple
    'Free-Speech-Red
    'Free-Speech-Red
    'Fire-Engine-Red
    'Crimson
    'Crimson
    'Ruby
    'Ruby
    'Ruby
    'Medium-Violet-Red
    'Hollywood-Cerise
    'Hollywood-Cerise
    'Shocking-Pink
    'Deep-Magenta
    'Deep-Magenta
    'Psychedelic-Purple
    'Psychedelic-Purple
    'Harley-Davidson-Orange
    'Harley-Davidson-Orange
    'Persian-Red
    'Alizarin
    'Crimson
    'Amaranth
    'Cerise
    'Deep-Cerise
    'Deep-Cerise
    'Deep-Cerise
    'Spicy-Pink
    'Shocking-Pink
    'Deep-Magenta
    'Deep-Magenta
    'Psychedelic-Purple
    'Psychedelic-Purple
    'Harley-Davidson-Orange
    'Harley-Davidson-Orange
    'Cinnabar
    'Persian-Red
    'Amaranth
    'Amaranth
    'Cerise
    'Deep-Cerise
    'Deep-Cerise
    'Deep-Cerise
    'Persian-Rose
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Free-Speech-Magenta
    'Free-Speech-Magenta
    'Psychedelic-Purple
    'Persimmon
    'Harley-Davidson-Orange
    'Cinnabar
    'Cinnabar
    'Cinnabar
    'Mandy
    'Cerise
    'Cranberry
    'Deep-Cerise
    'Deep-Cerise
    'Mulberry
    'Fuchsia
    'Free-Speech-Magenta
    'Free-Speech-Magenta
    'Free-Speech-Magenta
    'Heliotrope
    'Persimmon
    'Persimmon
    'Chilean-Fire
    'Chilean-Fire
    'Valencia
    'Valencia
    'Cabaret
    'Cranberry
    'Dark-Pink
    'Mulberry
    'Brilliant-Rose
    'Free-Speech-Magenta
    'Free-Speech-Magenta
    'Free-Speech-Magenta
    'Free-Speech-Magenta
    'Heliotrope
    'Mango-Tango
    'Chocolate
    'Chocolate
    'Sorbus
    'Flamingo
    'Flamingo
    'Roman
    'Froly
    'Deep-Blush
    'Pale-Violet-Red
    'Hopbush
    'Orchid
    'Orchid
    'Orchid
    'Heliotrope
    'Heliotrope
    'Mango-Tango
    'Mango-Tango
    'Tahiti-Gold
    'Tahiti-Gold
    'Jaffa
    'Terra-Cotta
    'Terra-Cotta
    'Geraldine
    'Deep-Blush
    'Pale-Violet-Red
    'Pale-Violet-Red
    'Persian-Pink
    'Orchid
    'Orchid
    'Heliotrope
    'Heliotrope
    'Tangerine
    'Gamboge
    'Buttercup
    'Tree-Poppy
    'Tree-Poppy
    'Whiskey-Sour
    'Copper
    'New-York-Pink
    'Sea-Pink
    'Carissma
    'Kobi
    'Shocking
    'Orchid
    'Plum
    'Violet
    'Heliotrope
    'Gamboge
    'Gamboge
    'Buttercup
    'Buttercup
    'Fire-Bush
    'Porsche
    'Porsche
    'Feldspar
    'Tonys-Pink
    'Petite-Orchid
    'Kobi
    'Shocking
    'Plum
    'Plum
    'Plum
    'Mauve
    'Gamboge
    'Gamboge
    'Galliano
    'Tulip-Tree
    'Tulip-Tree
    'Rob-Roy
    'Equator
    'Manhattan
    'Tumbleweed
    'Rose
    'Oyster-Pink
    'Melanie
    'Maverick
    'Plum
    'Mauve
    'Mauve
    'Sunflower
    'Sunflower
    'Sunflower
    'Metallic-Gold
    'Old-Gold
    'Ronchi
    'Equator
    'Straw
    'Burly-Wood
    'Pancho
    'Just-Right
    'Cavern-Pink
    'Twilight
    'Thistle
    'Mauve
    'Mauve
    'Bird-Flower
    'Sunflower
    'Barberry
    'Wattle
    'Confetti
    'Confetti
    'Golden-Sand
    'Sandwisp
    'Sandwisp
    'Tahuna-Sands
    'Raffia
    'Swirl
    'Light-Grey
    'Thistle
    'Fog
    'Fog
    'Chartreuse-Yellow
    'Barberry
    'Bitter-Lemon
    'Starship
    'Starship
    'Manz
    'Goldenrod
    'Goldenrod
    'Primrose
    'Primrose
    'Tusk
    'Loafer
    'Green-White
    'Gainsboro
    'Quartz
    'Quartz
    'Chartreuse-Yellow
    'Chartreuse-Yellow
    'Pear
    'Pear
    'Starship
    'Honeysuckle
    'Mindaro
    'Mindaro
    'Jonquil
    'Reef
    'Reef
    'Snow-Flurry
    'Frostee
    'Tara
    'Oyster-Bay
    'Solitude
    'Chartreuse-Yellow
    'Chartreuse-Yellow
    'Chartreuse-Yellow
    'Pear
    'Pear
    'Honeysuckle
    'Mindaro
    'Mindaro
    'Tidal
    'Reef
    'Reef
    'Tea-Green
    'Hint-Of-Green
    'Tara
    'White-Ice
    'Light-Cyan
    'Red
    'Venetian-Red
    'Torch-Red
    'Torch-Red
    'Torch-Red
    'Razzmatazz
    'Razzmatazz
    'Razzmatazz
    'Hollywood-Cerise
    'Hollywood-Cerise
    'Hollywood-Cerise
    'Shocking-Pink
    'Hot-Magenta
    'Hot-Magenta
    'Magenta
    'Magenta
    'Red
    'Red
    'Torch-Red
    'Torch-Red
    'Crimson
    'Razzmatazz
    'Ruby
    'Ruby
    'Deep-Pink
    'Deep-Pink
    'Hollywood-Cerise
    'Shocking-Pink
    'Shocking-Pink
    'Hot-Magenta
    'Magenta
    'Psychedelic-Purple
    'Scarlet
    'Scarlet
    'Red-Orange
    'Alizarin
    'Amaranth
    'Amaranth
    'Cerise
    'Deep-Cerise
    'Deep-Pink
    'Persian-Rose
    'Spicy-Pink
    'Spicy-Pink
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Magenta
    'Psychedelic-Purple
    'Scarlet
    'Scarlet
    'Cinnabar
    'Cinnabar
    'Amaranth
    'Amaranth
    'Cerise
    'Cerise
    'Deep-Cerise
    'Wild-Strawberry
    'Persian-Rose
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Psychedelic-Purple
    'Orange-Red
    'Orange-Red
    'Cinnabar
    'Cinnabar
    'Coral-Red
    'Radical-Red
    'Radical-Red
    'Dark-Pink
    'Violet-Red
    'Violet-Red
    'Brilliant-Rose
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Free-Speech-Magenta
    'Free-Speech-Magenta
    'Pink-Flamingo
    'Persimmon
    'Persimmon
    'Outrageous-Orange
    'Outrageous-Orange
    'Sunset-Orange
    'Flamingo
    'Wild-Watermelon
    'Dark-Pink
    'Dark-Pink
    'Brilliant-Rose
    'Brilliant-Rose
    'Hot-Pink
    'Free-Speech-Magenta
    'Free-Speech-Magenta
    'Free-Speech-Magenta
    'Pink-Flamingo
    'Persimmon
    'Persimmon
    'Tahiti-Gold
    'Sorbus
    'Tomato
    'Flamingo
    'Bittersweet
    'Froly
    'Deep-Blush
    'Pale-Violet-Red
    'Hot-Pink
    'Hot-Pink
    'Neon-Pink
    'Free-Speech-Magenta
    'Pink-Flamingo
    'Pink-Flamingo
    'Mango-Tango
    'Pumpkin
    'Pumpkin
    'Pizazz
    'Jaffa
    'Burnt-Sienna
    'Terra-Cotta
    'Geraldine
    'Deep-Blush
    'Carissma
    'Tickle-Me-Pink
    'Persian-Pink
    'Neon-Pink
    'Pale-Magenta
    'Violet
    'Heliotrope
    'Tangerine
    'Tangerine
    'Carrot-Orange
    'Sun
    'Flamenco
    'Crusta
    'Crusta
    'Salmon
    'Sweet-Pink
    'Wewak
    'Mauvelous
    'Persian-Pink
    'Tea-Rose
    'Pale-Magenta
    'Violet
    'Violet
    'Gamboge
    'Gamboge
    'Carrot-Orange
    'Yellow-Sea
    'Sea-Buckthorn
    'Sea-Buckthorn
    'Sandy-Brown
    'Dark-Salmon
    'Tonys-Pink
    'Sweet-Pink
    'Illusion
    'Shocking
    'Shocking
    'Lavender-Rose
    'Violet
    'Violet
    'Orange
    'Dark-Tangerine
    'Gold-Tips
    'Lightning-Yellow
    'Tulip-Tree
    'Casablanca
    'Sandy-Brown
    'Tacao
    'Tonys-Pink
    'Wax-Flower
    'Sundown
    'Cupid
    'Lavender-Pink
    'Lavender-Rose
    'Plum
    'Mauve
    'Golden-Poppy
    'Moon-Yellow
    'Moon-Yellow
    'Bright-Sun
    'Cream-Can
    'Ronchi
    'Harvest-Gold
    'Corvette
    'Corvette
    'Mandys-Pink
    'Zinnwaldite
    'Beauty-Bush
    'Chantilly
    'French-Lilac
    'French-Lilac
    'Mauve
    'Tangerine-Yellow
    'Moon-Yellow
    'Broom
    'Golden-Dream
    'Festival
    'Portica
    'Golden-Sand
    'Marzipan
    'Marzipan
    'Chamois
    'Desert-Sand
    'Watusi
    'Vanilla-Ice
    'Classic-Rose
    'Snuff
    'Blue-Chalk
    'Golden-Yellow
    'Lemon
    'Golden-Fizz
    'Golden-Fizz
    'Starship
    'Portica
    'Golden-Sand
    'Light-Goldenrod
    'Light-Goldenrod
    'Splash
    'Sidecar
    'Dutch-White
    'Almond
    'Soft-Peach
    'Selago
    'Magnolia
    'Lemon
    'Lemon
    'Golden-Fizz
    'Golden-Fizz
    'Paris-Daisy
    'Paris-Daisy
    'Honeysuckle
    'Dolly
    'Tidal
    'Portafino
    'Medium-Goldenrod
    'Chiffon
    'Spring-Sun
    'Sugar-Cane
    'Whisper
    'Lavender
    'Chartreuse-Yellow
    'Chartreuse-Yellow
    'Lemon
    'Golden-Fizz
    'Paris-Daisy
    'Laser-Lemon
    'Laser-Lemon
    'Dolly
    'Tidal
    'Tidal
    'Australian-Mint
    'Snow-Flurry
    'Snow-Flurry
    'Panache
    'Honeydew
    'Azure
    'Red
    'Torch-Red
    'Torch-Red
    'Torch-Red
    'Torch-Red
    'Razzmatazz
    'Razzmatazz
    'Deep-Pink
    'Deep-Pink
    'Hollywood-Cerise
    'Hollywood-Cerise
    'Shocking-Pink
    'Hot-Magenta
    'Hot-Magenta
    'Magenta
    'Magenta
    'Red
    'Red
    'Torch-Red
    'Torch-Red
    'Torch-Red
    'Razzmatazz
    'Razzmatazz
    'Deep-Pink
    'Deep-Pink
    'Deep-Pink
    'Spicy-Pink
    'Shocking-Pink
    'Shocking-Pink
    'Hot-Magenta
    'Magenta
    'Magenta
    'Scarlet
    'Scarlet
    'Red-Orange
    'Torch-Red
    'Torch-Red
    'Radical-Red
    'Radical-Red
    'Deep-Pink
    'Deep-Pink
    'Persian-Rose
    'Spicy-Pink
    'Spicy-Pink
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Magenta
    'Magenta
    'Scarlet
    'Scarlet
    'Red-Orange
    'Red-Orange
    'Radical-Red
    'Radical-Red
    'Radical-Red
    'Radical-Red
    'Wild-Strawberry
    'Wild-Strawberry
    'Persian-Rose
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Magenta
    'Orange-Red
    'Orange-Red
    'Red-Orange
    'Red-Orange
    'Coral-Red
    'Radical-Red
    'Radical-Red
    'Violet-Red
    'Violet-Red
    'Wild-Strawberry
    'Brilliant-Rose
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Razzle-Dazzle-Rose
    'Pink-Flamingo
    'Pink-Flamingo
    'International-Orange
    'International-Orange
    'Outrageous-Orange
    'Outrageous-Orange
    'Sunset-Orange
    'Sunset-Orange
    'Wild-Watermelon
    'Wild-Watermelon
    'French-Rose
    'Brilliant-Rose
    'Brilliant-Rose
    'Hot-Pink
    'Neon-Pink
    'Free-Speech-Magenta
    'Pink-Flamingo
    'Pink-Flamingo
    'Safety-Orange
    'Pumpkin
    'Pumpkin
    'Outrageous-Orange
    'Tomato
    'Bittersweet
    'Bittersweet
    'Wild-Watermelon
    'Brink-Pink
    'Brilliant-Rose
    'Hot-Pink
    'Hot-Pink
    'Neon-Pink
    'Neon-Pink
    'Pink-Flamingo
    'Pink-Flamingo
    'Safety-Orange
    'Pumpkin
    'Pumpkin
    'Burnt-Orange
    'Coral
    'Coral
    'Bittersweet
    'Salmon
    'Brink-Pink
    'Tickle-Me-Pink
    'Tickle-Me-Pink
    'Persian-Pink
    'Neon-Pink
    'Pale-Magenta
    'Pale-Magenta
    'Fuchsia-Pink
    'Dark-Orange
    'Dark-Orange
    'Carrot-Orange
    'Sun
    'Coral
    'Coral
    'Salmon
    'Salmon
    'Light-Coral
    'Wewak
    'Tickle-Me-Pink
    'Tea-Rose
    'Tea-Rose
    'Pale-Magenta
    'Pale-Magenta
    'Fuchsia-Pink
    'Orange-Peel
    'Dark-Tangerine
    'Neon-Carrot
    'Neon-Carrot
    'Sunshade
    'Sunshade
    'Atomic-Tangerine
    'Light-Salmon
    'Mona-Lisa
    'Mona-Lisa
    'Mauvelous
    'Carnation-Pink
    'Carnation-Pink
    'Lavender-Rose
    'Lavender-Rose
    'Violet
    'Orange
    'Dark-Tangerine
    'Dark-Tangerine
    'Supernova
    'Yellow-Orange
    'Texas-Rose
    'Rajah
    'Hit-Pink
    'Light-Salmon
    'Rose-Bud
    'Sundown
    'Light-Pink
    'Carnation-Pink
    'Lavender-Pink
    'Lavender-Rose
    'Lavender-Rose
    'Selective-Yellow
    'Selective-Yellow
    'Moon-Yellow
    'Supernova
    'Yellow-Orange
    'Koromiko
    'Rajah
    'Macaroni-And-Cheese
    'Macaroni-And-Cheese
    'Mandys-Pink
    'Melon
    'Your-Pink
    'Pink
    'Cotton-Candy
    'Lavender-Rose
    'Lavender-Rose
    'Tangerine-Yellow
    'Tangerine-Yellow
    'Turbo
    'Sunglow
    'Sunglow
    'Kournikova
    'Grandis
    'Grandis
    'Cherokee
    'Peach-Orange
    'Peach
    'Your-Pink
    'Cosmos
    'Pink-Lace
    'Classic-Rose
    'Snuff
    'Golden-Yellow
    'Lemon
    'Turbo
    'Gorse
    'Gorse
    'Mustard
    'Dandelion
    'Sweet-Corn
    'Golden-Glow
    'Cream-Brulee
    'Navajo-White
    'Peach-Puff
    'Cinderella
    'Misty-Rose
    'Pig-Pink
    'Selago
    'Golden-Yellow
    'Lemon
    'Lemon
    'Gorse
    'Paris-Daisy
    'Paris-Daisy
    'Corn
    'Witch-Haze
    'Picasso
    'Drover
    'Banana-Mania
    'Oasis
    'Blanched-Almond
    'Bridal-Heath
    'White-Smoke
    'Selago
    'Yellow
    'Yellow
    'Lemon
    'Gorse
    'Paris-Daisy
    'Laser-Lemon
    'Laser-Lemon
    'Laser-Lemon
    'Canary
    'Canary
    'Shalimar
    'Cumulus
    'Cream
    'Light-Yellow
    'Ivory
    'White))

(log-message knotty-logger 'info "end of colors.rkt" #f)
;end
